version: '3.8'
services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always

  iot:
    build:
      context: ./web
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db