services:
  queue:
    image: rabbitmq:3.13
    env_file:
      - .env
    volumes:
      - queue_data:/var/lib/rabbitmq
    restart: unless-stopped

  db:
    build: ./db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
        - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  db_optimizer:
    build: ./db_optimizer
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
    depends_on:
      - db
    restart: unless-stopped

  web:
    build:
      context: ./web
    env_file:
      - .env
    environment:
      - SPRING_RABBITMQ_HOST=queue
      - SPRING_RABBITMQ_PORT=5672
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    restart: unless-stopped

volumes:
    db_data:
    queue_data: