spring:
  application:
    name: iot
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}

logging:
  level:
    org:
      springframework:
        security: DEBUG