spring:
  application:
    name: iot
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      org.hibernate.type.descriptor.sql: trace
      springframework:
        security: DEBUG